### ISSUE TITLE
How to build jobs that require sc options like --c++std=c++11

### ISSUE THREAD

**Issue by markheger** [IBMStreams/vscode-ide#100]
Some toolkit operators needs to be build with '`--c++std=c++11`' **sc** option. 

How can this be achieved with Streams extension in VsCode?

**Comment by markheger** [comment]
ok, figured out that I need to right click on Makefile and then build/submit

even toolkit location needs to be added to Makefile

-t $(STREAMS_INSTALL)/toolkits

How to specify toolkit location for additional toolkits (added from local dir to archive)?

**Comment by queeniema** [comment]
That's correct. If you are building from a `Makefile` *and* your application depends on Streams toolkits (the Streams product toolkits and/or local toolkits that you've added to the **Toolkit Paths** setting in VS Code), then you must manually add the `-t` option to the [`sc`](https://www.ibm.com/support/knowledgecenter/SSCRJU_4.3.0/com.ibm.streams.ref.doc/doc/sc.html) command:

```
-t $(STREAMS_INSTALL)/toolkits:../toolkits
```

- For Streams product toolkits, add the path: `$(STREAMS_INSTALL)/toolkits`
- For local toolkits, add the path: `../toolkits`
