### ISSUE TITLE
Warning for unsaved changes in files other than spl

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/vscode-ide#103]
If an .spl file has unsaved changes and I try to build, we have now a dialouge that warns see issue #70. But the same should apply to all files which are relevant for the build process. Especially if the info.xml file is unsaved, we should warn the user.

**Comment by queeniema** [comment]
We now warn the user if there are _any_ files with unsaved changes (not just relevant files for a build).

If there is only one file with unsaved changes:

<img width="467" alt="single" src="https://user-images.githubusercontent.com/2454818/85448387-7c408800-b54b-11ea-8731-4ebaea30a7bd.png">

If there are multiple files with unsaved changes:

<img width="466" alt="multiple" src="https://user-images.githubusercontent.com/2454818/85448441-8a8ea400-b54b-11ea-866c-92264e457791.png">

If there are multiple files with unsaved changes and the user selects **Choose Files to Save**:

<img width="619" alt="multiple-select" src="https://user-images.githubusercontent.com/2454818/85448454-8d899480-b54b-11ea-8556-65a473ca936a.png">
