### ISSUE TITLE
SPL Mixe Mode

### ISSUE THREAD

**Issue by jchailloux** [IBMStreams/vscode-ide#109]
Is there any plan to support splmm ?

**Comment by petenicholls** [comment]
Not a this point.   Mixed mode has not been enhanced in a few years and with the introduction of user defined parallel regions alternative approaches where available.

**Comment by jchailloux** [comment]
splmm is more used to generate and configure SPL regarding config files.
It means that we still have to use StreamsStudio to generate the SPL from SPLMM.

**Comment by queeniema** [comment]
This is now available in toleration mode in the latest version of the extension (v1.0.3). Learn more [here](https://github.com/IBMStreams/vscode-ide/wiki/Working-with-mixed-mode-SPL-applications).
