### ISSUE TITLE
code completions -- turn off fuzzy matching

### ISSUE THREAD

**Issue by petenicholls** [IBMStreams/vscode-ide#12]
Code completions show "Fuzzy" matching.  For example, File shows anything with file in it, should just show things that actually start with file

**Comment by queeniema** [comment]
This seems to behave fine. The results that are given high priority are the ones that start with `file`, as expected. The other results that contain `file` are still valid and are useful to have in some cases.

![screen shot 2018-12-05 at 12 01 25 pm](https://user-images.githubusercontent.com/2454818/49540704-99d4d080-f885-11e8-89c5-b1b4e59c63a2.png)
