### ISSUE TITLE
Add actions to manage local toolkts in toolkit pane

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/vscode-ide#131]
Consider adding  an action to add a toolkit location from the toolkit pane. This could allow you to browse to the folder location in your file system, and then add that location to the list of toolkit locations. This is a bit more user friendly than having to manually edit locations in the settings.

It would also be nice to be able to click a local toolkit from the list and open its location in the file explorer. Right now you have to open the settings to find the exact folder and manually open it in explorer.

**Comment by queeniema** [comment]
This is now available in the latest version of the extension (v1.0.3).
