### ISSUE TITLE
Bad completions -- annotations

### ISSUE THREAD

**Issue by petenicholls** [IBMStreams/vscode-ide#14]
@parallel ( then ask for completions and you get key which is not allowed and makes no sense.

**Comment by queeniema** [comment]
I do not see this issue anymore. In the latest version of the extension, we show `width`, which is the only required element for the `@parallel` annotation (documentation [here](https://www.ibm.com/support/knowledgecenter/SSCRJU_4.3.0/com.ibm.streams.ref.doc/doc/udpparallelannotation.html)). Closing this issue. If you see it again, feel free to re-open the issue.

<img width="1513" alt="Screen Shot 2020-06-01 at 4 26 24 PM" src="https://user-images.githubusercontent.com/2454818/83464216-02721e80-a425-11ea-827b-f08bf25a2cd4.png">
