### ISSUE TITLE
submit dialog has wrong image

### ISSUE THREAD

**Issue by petenicholls** [IBMStreams/vscode-ide#18]
The submit selection message has default vscode image, should be IBM Streaming Analytics image

**Comment by queeniema** [comment]
I can't find a way to set the icon. I opened this feature request in the vscode repository: https://github.com/Microsoft/vscode/issues/63821.

**Comment by queeniema** [comment]
Closing this as the UI changed in https://github.com/IBMStreams/vscode-ide/commit/d56afcf82106f875de6fd22950306e535c1aa060 (using notification instead of modal dialog).
