### ISSUE TITLE
submit via console link disappears

### ISSUE THREAD

**Issue by petenicholls** [IBMStreams/vscode-ide#19]
When user selects submit via console, the information pop-up disappears without dismissal and no way to get it back.  Should be visible until user clicks or closes.

**Comment by queeniema** [comment]
The latest VS Code (October 2018, version 1.29) introduced a new [change](https://code.visualstudio.com/updates/v1_29#_notifications-automatically-hide-even-when-showing-buttons):

>Notifications are hidden after a timeout even if they show buttons.

To get around this, we'll show another dialog instead of a notification popup.
