### ISSUE TITLE
js-yaml vulnerability found in package-lock.json

### ISSUE THREAD

**Issue by schubon** [IBMStreams/vscode-ide#45]
### Details
WS-2019-0063
high severity
Vulnerable versions: < 3.13.1
Patched version: 3.13.1

Js-yaml prior to 3.13.1 are vulnerable to Code Injection. The load() function may execute arbitrary code injected through a malicious YAML file.

### Remediation

Upgrade js-yaml to version 3.13.1 or later. For example:

```
"dependencies": {
  "js-yaml": ">=3.13.1"
}

```
or…

```
"devDependencies": {
  "js-yaml": ">=3.13.1"
}

```
Always verify the validity and compatibility of suggestions with your codebase.

**Comment by queeniema** [comment]
Used the GitHub tool to automatically generate a fix. See https://github.com/IBMStreams/vscode-ide/pull/47.

**Comment by queeniema** [comment]
<img width="428" alt="Screen Shot 2019-07-01 at 2 08 33 PM" src="https://user-images.githubusercontent.com/2454818/60466883-c9746d00-9c09-11e9-9b3f-2c205e274212.png">
