### ISSUE TITLE
Expired JWT Token

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/vscode-ide#59]
Not sure if  I had VSCode open for too long, but I got this error when trying to submit:
`CDISB5033E The authentication credentials could not be validated. Error is: 'jwt expired at 2019-08-16T02:39:14+0000, current time is 2019-08-16T04:41:12+0000 with leeway of 0 ms'.`
Had to quit and restart.

**Comment by queeniema** [comment]
I believe this has been fixed in the latest version of the extension, so I am closing this issue. If you see this again, feel free to re-open the issue.
