### ISSUE TITLE
Vulnerability in "https-proxy-agent" found in package-lock.json

### ISSUE THREAD

**Issue by schubon** [IBMStreams/vscode-ide#68]
#### WS-2019-0310
moderate severity
Vulnerable versions: < 2.2.3
Patched version: 2.2.3

There is a Machine-In-The-Middle vulnerability found in https-proxy-agent before 2.2.3. There is a failure of TLS enforcement on the socket. Attacker may intercept unencrypted communications.

### Remediation

Upgrade https-proxy-agent to version 2.2.3 or later. For example:

```
"dependencies": {
  "https-proxy-agent": ">=2.2.3"
}
```

or…

```
"devDependencies": {
  "https-proxy-agent": ">=2.2.3"
}
```

Always verify the validity and compatibility of suggestions with your codebase.

**Comment by schubon** [comment]
see pull request #67

**Comment by queeniema** [comment]
`https-proxy-agent` has been updated so this is no longer an issue.
