### ISSUE TITLE
Warning for unsaved changes

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/vscode-ide#70]
When I build a spl and there are unsaved changes in the editor window, the tool should emit a warning about the unsaved changes.

**Comment by queeniema** [comment]
<img width="1344" alt="Screen Shot 2020-06-08 at 12 21 13 PM" src="https://user-images.githubusercontent.com/2454818/84071460-96db0480-a982-11ea-81ff-d981b2fb6da7.png">

**Comment by joergboe** [comment]
resolved in v1.0.1
