### ISSUE TITLE
Better support for job configuration overlay files when configuring job submissions

### ISSUE THREAD

**Issue by queeniema** [IBMStreams/vscode-ide#81]
In the submit job configuration form:

- Move the **Import job configuration overlay file** button to the top
- When importing and exporting files, use the _bundle directory_ (when submitting from an application bundle using the **Submit Job** command) or _application root directory_ (when submitting from a SPL or Makefile file using the **Build and Submit Job** command) as the default directory (rather than the user's home directory)
- Show the imported file name and errors if there are any (i.e., invalid structure or invalid JSON)

**Comment by queeniema** [comment]
@joergboe Would you want to see an actual list of job configuration overlay files in the form? Something like the following (where `test.json` and `test2.json` are in the same directory):

<img width="366" alt="Screen Shot 2020-06-05 at 10 53 01 AM" src="https://user-images.githubusercontent.com/2454818/83910756-f2f21e80-a71f-11ea-8fad-e317c5974558.png">

Or in the file selection dialog, use the bundle directory as the default directory (rather than the user's home directory)?

<img width="1443" alt="Screen Shot 2020-06-05 at 11 29 00 AM" src="https://user-images.githubusercontent.com/2454818/83910789-043b2b00-a720-11ea-9ce1-9fb9056362e7.png">

In my opinion, I think the list of files looks a little odd and I would prefer the second option.

**Comment by joergboe** [comment]
I prefer the second option.

**Comment by queeniema** [comment]
Scenario | Screenshot
---|---
default | <img width="982" alt="default" src="https://user-images.githubusercontent.com/2454818/84079766-f390ec00-a98f-11ea-8f66-169c9c7ea23d.png">
valid | <img width="982" alt="good" src="https://user-images.githubusercontent.com/2454818/84079765-f390ec00-a98f-11ea-860e-6203073790f1.png">
invalid | <img width="982" alt="invalid" src="https://user-images.githubusercontent.com/2454818/84079753-f12e9200-a98f-11ea-9e78-d476a7ba8da5.png">
invalid JSON | <img width="982" alt="bad" src="https://user-images.githubusercontent.com/2454818/84079762-f2f85580-a98f-11ea-9fa1-72ec5f015a77.png">
