### ISSUE TITLE
Special characters in default values for submission-time parameters are not being handled correctly

### ISSUE THREAD

**Issue by queeniema** [IBMStreams/vscode-ide#82]
Consider a SPL application that has these parameters defined:

```
expression<list<rstring>> $colours:
    (list<rstring>) getSubmissionTimeValue("colours", "[\"green\n***\", \"yellow\", \"red\"]");
expression<rstring> $astring:
    getSubmissionTimeValue("astring", "*** line 1 ***\n*** line2 ***");
```

When submitting the application with the default values (i.e., by not modifying anything in the configure job submission panel), the job is unhealthy.

`CDISR5057E: The conversion from the [\"green\n***\", \"yellow\", \"read\"] string to a C++ type of SPL::list<SPL::rstring> did not succeed.`

---

As part of this issue: If a user does not modify the default value of a submission-time parameter, then we should omit sending the value in the job configuration overlay when submitting the job.

**Comment by joergboe** [comment]
seems to work in v1.0.1
