### ISSUE TITLE
Annotations not coloring correctly

### ISSUE THREAD

**Issue by petenicholls** [IBMStreams/vscode-ide#9]
Annotations should be in keyword color.

**Comment by petenicholls** [comment]
autonomous not right yet

**Comment by queeniema** [comment]
This has been fixed, closing this issue. If you still see this issue in the latest version of the extension, feel free to re-open the issue.

<img width="1513" alt="Screen Shot 2020-06-01 at 4 35 05 PM" src="https://user-images.githubusercontent.com/2454818/83464486-e58a1b00-a425-11ea-8d2f-2ed57a28f844.png">
